# Generated by Django 4.0.4 on 2022-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('dish', '0002_dish_photo_menucategory_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='delete',
        ),
        migrations.AddField(
            model_name='dish',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='branches',
            field=models.ManyToManyField(to='restaurant.branch'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
