# Generated by Django 3.2 on 2022-04-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_remove_dish_delete_dish_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='since',
            new_name='since_date',
        ),
    ]
