# Generated by Django 3.2 on 2022-04-18 14:51

import dish.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_rename_since_promotion_since_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[dish.validations.validator_no_negative]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[dish.validations.validator_no_negative]),
        ),
    ]
