# Generated by Django 4.0.4 on 2022-04-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_active_restaurant_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='max_admins',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='max_branches',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
