# Generated by Django 4.0.4 on 2022-04-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_max_admins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
