version: '3.9'

services:
  web:
    container_name: restaurants_app
    image: restaurants_app
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/postgres/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db-restaurants_app
    ports:
      - "7000:5432"


volumes:
  pg_data: {}
